---
# vars file for hashicorp_nomad
hashi_nomad_user: nomad
hashi_nomad_group: nomad
hashi_nomad_config_dir: "/etc/nomad.d"
hashi_nomad_cni_plugins_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm'
  armv7l: 'arm'
  armv6l: 'arm'
hashi_nomad_cni_plugins_arch: "{{ hashi_nomad_cni_plugins_arch_map[ansible_architecture] | default(ansible_architecture) }}"
hashi_nomad_cni_plugins_github_api: https://api.github.com/repos/containernetworking/plugins
hashi_nomad_cni_plugins_github_url: https://github.com/containernetworking/plugins
hashi_nomad_repository:
  - name: hashicorp
    uri: "https://apt.releases.hashicorp.com"
    comments: "hashicorp repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    options:
      Signed-By: "https://apt.releases.hashicorp.com/gpg"
hashi_nomad_packages:
  - name: nomad
    version: "{{ hashi_nomad_version }}"
    state: "{% if hashi_nomad_auto_update %}latest{% else %}present{% endif %}"
