---
# meta file for hashistack
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "hashistack"
  author: "Bertrand Lanson"
  description: "Merge variables for the playbooks contained in ednz_cloud.hashistack collection"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "hashicorp"

dependencies: []
