---
###############
# cni plugins #
###############

hashistack_default_cni_plugins_version: "v1.5.1"
cni_plugins_version: "{{ hashistack_cni_plugins_version | default(hashistack_default_cni_plugins_version) }}"

hashistack_default_cni_plugins_install_path: /opt/cni/bin
cni_plugins_install_path: "{{ hashistack_cni_plugins_install_path | default(hashistack_default_cni_plugins_install_path) }}"

hashistack_default_cni_plugins_install_consul_cni: true
cni_plugins_install_consul_cni: "{{ hashistack_cni_plugins_install_consul_cni | default(hashistack_default_cni_plugins_install_consul_cni) }}"

hashistack_default_cni_user: nomad
cni_user: "{{ hashistack_cni_user | default(hashistack_default_cni_user) }}"

hashistack_default_cni_group: nomad
cni_group: "{{ hashistack_cni_group | default(hashistack_default_cni_group) }}"
