---
name: development
on:
  push:
    branches-ignore:
      - main

jobs:
  commit-check:
    name: Check commit compliance
    uses: https://git.ednz.fr/github-actions/library/.gitea/workflows/cz-commit-check.yml@v0.1.0
