---
name: end-to-end-tests-vault
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - .gitea/workflows/e2e-tests-vault.yml
      - roles/vault/**
      - molecule/vault__**

jobs:
  retrieve-credentials:
    name: Retrieve Credentials
    runs-on: ubuntu-latest
    outputs:
      registry-username: ${{ steps.import-secrets.outputs.GITEA_ACTIONS_USERNAME }}
      registry-token: ${{ steps.import-secrets.outputs.GITEA_ACTIONS_TOKEN }}
      vault-token: ${{ steps.generate-vault-token.outputs.VAULT_TOKEN }}
    steps:
      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/applications/gitea/users/actions username | GITEA_ACTIONS_USERNAME ;
            kv/data/applications/gitea/users/actions token_write | GITEA_ACTIONS_TOKEN ;

      - name: Generate Vault token
        id: generate-vault-token
        run: |
          VAULT_TOKEN=$(curl --silent --request POST --data '{"role_id": "${{ secrets.VAULT_APPROLE_ID }}","secret_id": "${{ secrets.VAULT_APPROLE_SECRET_ID }}"}' https://vault.ednz.fr/v1/auth/approle/login | jq -r .auth.client_token)

          echo "vault_token=$VAULT_TOKEN" >> $GITHUB_OUTPUT

  end_to_end_test:
    name: End to End Test
    runs-on: ubuntu-latest
    needs: retrieve-credentials
    strategy:
      matrix:
        test_config:
          - test_os: "Debian 11 bullseye"
            test_user: "debian"
          - test_os: "Debian 12 bookworm"
            test_user: "debian"
          - test_os: "Ubuntu 20.04 LTS Focal Fossa"
            test_user: "ubuntu"
          - test_os: "Ubuntu 22.04 LTS Jammy Jellyfish"
            test_user: "ubuntu"
          - test_os: "Ubuntu 24.04 LTS Noble Numbat"
            test_user: "ubuntu"
        scenario:
          - vault__default__openstack
          - vault__with_raft_enabled__openstack
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate OpenStack cloud file
        uses: https://git.ednz.fr/github-actions/library/.gitea/actions/generate-cloud-config@v0.3.0
        with:
          vault_addr: https://vault.ednz.fr
          vault_token: ${{ needs.retrieve-credentials.outputs.vault-token }}

      - name: Run end-to-end tests
        uses: https://git.ednz.fr/github-actions/library/.gitea/actions/molecule-e2e-test@v0.3.0
        with:
          role: vault
          scenario: ${{ matrix.scenario }}
          test_os: ${{ matrix.test_config.test_os }}
          test_user: ${{ matrix.test_config.test_user }}
          is_openstack: "true"
          os_cloud: pcp-w3rxsrj-dc4-a
