---
name: pull-requests-open
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  commit-history-check:
    name: Commit History Check
    uses: https://git.ednz.fr/github-actions/library/.gitea/workflows/cz-pull-request-check.yml@v0.1.0
