---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Test: packages mariadb-server, apache2, consul:1.13.1-1"
      block:
        - name: "Get packages facts"
          ansible.builtin.package_facts:
            manager: auto

        - name: "Verify packages mariadb-server, apache2, consul:1.13.1-1"
          ansible.builtin.assert:
            that:
              - "ansible_facts.packages['mariadb-server'][0]['name'] == 'mariadb-server'"
              - "ansible_facts.packages['apache2'][0]['name'] == 'apache2'"
              - "ansible_facts.packages['consul'][0]['name'] == 'consul'"
              - "ansible_facts.packages['consul'][0]['version'] == '1.13.1-1'"
