---
dependency:
  name: galaxy
  options:
    requirements-file: ../requirements.yml
driver:
  name: docker
platforms:
  - name: consul-vault
    image: geerlingguy/docker-${MOLECULE_TEST_OS}-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - common
      - consul_servers
      - vault_servers
  - name: vault-nomad
    image: geerlingguy/docker-${MOLECULE_TEST_OS}-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - common
      - nomad_clients
      - vault_servers
  - name: nomad-consul
    image: geerlingguy/docker-${MOLECULE_TEST_OS}-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - common
      - nomad_clients
      - consul_agents
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
scenario:
  name: hashistack_ca_default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
