---
# defaults file for hashicorp_nomad

#####################
# ACL configuration #
#####################

nomad_acl_configuration:
  enabled: true
  token_ttl: 30s
  policy_ttl: 60s
  role_ttl: 60s
