---
# meta file for consul
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "consul"
  author: "Bertrand Lanson"
  description: "Install and configure hashicorp consul for debian-based distros."
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "hashicorp"
    - "consul"

dependencies: []
