---
# hashistack generate certificates playbook
- name: "Generate certificates"
  hosts: common
  strategy: linear
  gather_facts: true
  become: true
  tasks:
    - name: "Import variables"
      ansible.builtin.include_role:
        name: ednz_cloud.hashistack.hashistack
      tags:
        - always

    - name: "Create Certificate Authority"
      ansible.builtin.include_role:
        name: ednz_cloud.hashistack.hashistack_ca
        apply:
          delegate_to: localhost
      tags:
        - always
