---
- name: Include credentials generation playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.credentials.yml

- name: Include bootstrap playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.bootstrap.yml

- name: Include preflight playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.preflight.yml
